### PR TITLE
plot schematic as svg

### PR DESCRIPTION
**Pull request by nerdyscout**
small addition to enable plotting schematic as svg.

thank your for kiplot, this really rocks!

### CODE REVIEW

**Comment by set-soft** [comment]
Hi!
Sorry for the big delay. I was too busy testing the new internal BoM generator that I overlooked your PR.
It crossed my mind a couple of times "why did I name pdf_sch_print when the script can generate other formats?"
But never added them.
Thanks for taking the time to add it!

BTW: Do you want to provide a real name instead of your nick name?
I'm adding proper copyrights to the files.

Also: I'm also scout ... not fully involved, but I was involved for 10 years aprox. Now my son is scout too!

Grüße, SET

**Comment by nerdyscout** [comment]
no worries @set-soft!
I was watching your changes to the 'load_schematic' branch from time to time and already suspected you to be very busy there.

Thank you for this great kiplot/kibot project! You might have noticed my kicad-export tool which would be nothing without kiplot.
Actually I think my little contribution is not notable, feel free to remove my name. If not please at least fix the missing r. 

10 years do not sound like like "not fully involved" :laughing:

**Comment by set-soft** [comment]
> Thank you for this great kiplot/kibot project! 

:-)

> You might have noticed my kicad-export tool

Yes! Very nice collection! 
I didn't know about PcbDraw. I added support after discovering it in kicad-export.
BTW: What about creating separated actions for ERC and DRC? In this way a project can quickly add them as separated pipelines and have their status. Then the user could choose to use their outcomes to trigger the generation of other stuff.

>  which would be nothing without kiplot.

Thanks, but not all is currently covered. I wish to add KiKit and KiCost support.
But I have too much things in mind, and when I played with PcbDraw ... was a lot of time invested.

> Actually I think my little contribution is not notable, feel free to remove my name.

A contribution is always welcome, no matters if this is a detail. And even when simple is another output.

>  If not please at least fix the missing r.

Oops! please tell me where is missing. In the file header I used:

```
# Copyright (c) 2020 @nerdyscout
```

> 10 years do not sound like like "not fully involved" ￼

Ok, ok ...

**Comment by set-soft** [comment]
> Oops! please tell me where is missing. In the file header I used:

I found it! Was in the README.md not in the file itself. 
Fixed, sorry.

**Comment by nerdyscout** [comment]
> > Oops! please tell me where is missing. In the file header I used:
> 
> I found it! Was in the README.md not in the file itself.
> Fixed, sorry.

thank you a lot!

**Pull request merged**
